import React from "react";
import Link from "next/link";
import { CertificateService } from "@/features/certificates/certificate.service";
import { formatDate } from "@/lib/utils";
import { Award, Download, Eye, Search, ExternalLink, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

export const dynamic = "force-dynamic";

export default async function AdminCertificatesPage() {
  let certificates: any[] = [];

  try {
    certificates = await CertificateService.getAllCertificates(200);
  } catch (err) {
    console.error("Fetch certificates error:", err);
  }

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Top Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-white tracking-tight font-serif">
            Issued Certificates Registry ({certificates.length})
          </h2>
          <p className="text-xs text-slate-400">
            Active World Book of Record Excellence certificates generated by the system.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <Link href="/verify" target="_blank">
            <Button variant="outline" size="sm" className="h-9 text-xs">
              <ExternalLink className="h-3.5 w-3.5 mr-1.5" />
              Public Verification Portal
            </Button>
          </Link>
        </div>
      </div>

      {/* Table */}
      <div className="rounded-2xl border border-slate-800 bg-slate-900/80 shadow-xl overflow-hidden">
        {certificates.length === 0 ? (
          <div className="p-12 text-center text-slate-400 text-xs space-y-2">
            <Award className="h-8 w-8 mx-auto text-slate-600" />
            <p>No certificates issued yet.</p>
            <p className="text-[11px] text-slate-500">
              Certificates are automatically generated when applications are approved.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs text-slate-300">
              <thead className="bg-slate-950/70 text-slate-400 uppercase tracking-wider border-b border-slate-800 text-[11px]">
                <tr>
                  <th className="px-5 py-4">Record ID</th>
                  <th className="px-5 py-4">Certificate No</th>
                  <th className="px-5 py-4">Recipient Name</th>
                  <th className="px-5 py-4">Achievement Title</th>
                  <th className="px-5 py-4">Category & Place</th>
                  <th className="px-5 py-4">Issued Date</th>
                  <th className="px-5 py-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60">
                {certificates.map((cert) => (
                  <tr key={cert.id} className="hover:bg-slate-800/40 transition-colors">
                    <td className="px-5 py-3.5 font-mono font-bold text-amber-400">
                      {cert.recordId}
                    </td>
                    <td className="px-5 py-3.5 font-mono text-slate-200">
                      {cert.certificateNumber}
                    </td>
                    <td className="px-5 py-3.5 font-bold text-white">
                      {cert.recipientName}
                    </td>
                    <td className="px-5 py-3.5 max-w-[220px] truncate text-slate-200">
                      {cert.achievementTitle}
                    </td>
                    <td className="px-5 py-3.5">
                      <p className="text-slate-200">{cert.category}</p>
                      <p className="text-[11px] text-slate-400">{cert.place}</p>
                    </td>
                    <td className="px-5 py-3.5 text-slate-400 whitespace-nowrap">
                      {formatDate(cert.issueDate)}
                    </td>
                    <td className="px-5 py-3.5 text-right whitespace-nowrap">
                      <div className="flex items-center justify-end gap-2">
                        <Link href={`/certificate/${encodeURIComponent(cert.recordId)}`} target="_blank">
                          <Button variant="outline" size="sm" className="h-8 text-xs">
                            <Eye className="h-3.5 w-3.5 mr-1" />
                            Preview
                          </Button>
                        </Link>
                        <a
                          href={`/api/certificates/${encodeURIComponent(
                            cert.certificateNumber || cert.recordId
                          )}/download`}
                          download
                        >
                          <Button variant="gold" size="sm" className="h-8 text-xs font-semibold">
                            <Download className="h-3.5 w-3.5 mr-1" />
                            PDF
                          </Button>
                        </a>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
